-- Vytvoření tabulky student
CREATE TABLE student (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmeno      VARCHAR2(50),
    prijmeni   VARCHAR2(50)
);

-- Vytvoření tabulky kurz
CREATE TABLE kurz (
    kurz_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazev   VARCHAR2(100)
);

-- Vztahová tabulka student_kurz
CREATE TABLE student_kurz (
    student_id NUMBER,
    kurz_id    NUMBER,
    CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES student(student_id),
    CONSTRAINT fk_kurz FOREIGN KEY (kurz_id) REFERENCES kurz(kurz_id)
);
